version: '3.3'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}

  gui:
    container_name: gui
    build:
      context: ./gui
      dockerfile: Dockerfile
    expose:
      - ${GUI_PORT}
    ports:
      - ${GUI_PORT}:80
    environment:
      - API_PORT=${API_PORT}
    links:
      - api